Once upon a time in a forest, there lived a monkey who resided on a berry tree which was on the bank of the river. 
In the same forest, there lived a crocodile and his wife...
One day the crocodile came to the bank of the river and rested under the tree.
The kindhearted monkey offered him some fruits...

